"use client";
import Link from "next/link";
import "./globals.css";
import { useState,useEffect } from "react";
/*export const metadata = {
  title: "My First Next Js Project",
  description: "Generated by KCPL Boo SeonWoong",
};
*/
export default function RootLayout({ children }) {
  const [topics,setTopics] = useState([]);
  useEffect(()=>{
    fetch('http://localhost:9999/topic')
      .then(resp=>resp.json())
      .then(result=>{setTopics(result);});
  },[]);
  return (
    <html>
      <body >
        <ul>
          {
            topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })
          }
        </ul>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li>
        </ol>
        {children}
        <ul>
        <li><Link href="/create">create</Link></li>
        <li><Link href="/update/1">update</Link></li>
        <li><input type="button" value="delete"/></li>
        </ul>
      </body>
    </html>
  );
}
